waypoints:
  w_o:
  - 0.038553689930603124
  - 0.018032724703015007
  - 0.018032724703015007
  - 0.018032724703015007
  - 0.018032724703015007
  - 0.025391164829392358
  x:
  - 0.7117247117534721
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 1.0
  x_o:
  - 0.661855499510874
  - 0.7573911221500781
  - 0.7573911221500781
  - 0.7573911221500781
  - 0.7573911221500781
  - 0.9955332033401245
  y:
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  y_o:
  - 0.07996771861418568
  - 0.015973882152799247
  - 0.015973882152799247
  - 0.015973882152799247
  - 0.015973882152799247
  - 0.016201604331371935
  z:
  - 0.12924492625311704
  - 0.10200921643196453
  - 0.10200921643196453
  - 0.10200921643196453
  - 0.10200921643196453
  - 0.3424346639008812
  z_o:
  - 0.7443561477811472
  - 0.6525169300615881
  - 0.6525169300615881
  - 0.6525169300615881
  - 0.6525169300615881
  - 0.08947870033168155